# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-view1:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: './view'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.2'
        cache: 'npm'
        cache-dependency-path: './view/package-lock.json'
    - run: npm ci
    - run: npm run build
      env:
        REACT_APP_BUILD_ENV: 'prod'
    - name: Archive staging artifacts
      uses: actions/upload-artifact@v2
      with:
        name: prod-view1
        path: view/build

  build-view2:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: './view2'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.2'
        cache: 'npm'
        cache-dependency-path: './view2/package-lock.json'
    - run: npm ci
    - run: npm run build
      env:
        REACT_APP_BUILD_ENV: 'prod'
    - name: Archive staging artifacts
      uses: actions/upload-artifact@v2
      with:
        name: prod-view2
        path: view2/build
